/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sdmessage.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "sdmessage.pb-c.h"
void   data_message__init
                     (DataMessage         *message)
{
  static const DataMessage init_value = DATA_MESSAGE__INIT;
  *message = init_value;
}
size_t data_message__get_packed_size
                     (const DataMessage *message)
{
  assert(message->base.descriptor == &data_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t data_message__pack
                     (const DataMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &data_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t data_message__pack_to_buffer
                     (const DataMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &data_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DataMessage *
       data_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DataMessage *)
     protobuf_c_message_unpack (&data_message__descriptor,
                                allocator, len, data);
}
void   data_message__free_unpacked
                     (DataMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &data_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nullable_string__init
                     (NullableString         *message)
{
  static const NullableString init_value = NULLABLE_STRING__INIT;
  *message = init_value;
}
size_t nullable_string__get_packed_size
                     (const NullableString *message)
{
  assert(message->base.descriptor == &nullable_string__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nullable_string__pack
                     (const NullableString *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nullable_string__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nullable_string__pack_to_buffer
                     (const NullableString *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nullable_string__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NullableString *
       nullable_string__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NullableString *)
     protobuf_c_message_unpack (&nullable_string__descriptor,
                                allocator, len, data);
}
void   nullable_string__free_unpacked
                     (NullableString *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nullable_string__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   entry_message__init
                     (EntryMessage         *message)
{
  static const EntryMessage init_value = ENTRY_MESSAGE__INIT;
  *message = init_value;
}
size_t entry_message__get_packed_size
                     (const EntryMessage *message)
{
  assert(message->base.descriptor == &entry_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t entry_message__pack
                     (const EntryMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &entry_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t entry_message__pack_to_buffer
                     (const EntryMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &entry_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EntryMessage *
       entry_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EntryMessage *)
     protobuf_c_message_unpack (&entry_message__descriptor,
                                allocator, len, data);
}
void   entry_message__free_unpacked
                     (EntryMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &entry_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   keys_message__init
                     (KeysMessage         *message)
{
  static const KeysMessage init_value = KEYS_MESSAGE__INIT;
  *message = init_value;
}
size_t keys_message__get_packed_size
                     (const KeysMessage *message)
{
  assert(message->base.descriptor == &keys_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t keys_message__pack
                     (const KeysMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &keys_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t keys_message__pack_to_buffer
                     (const KeysMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &keys_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
KeysMessage *
       keys_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (KeysMessage *)
     protobuf_c_message_unpack (&keys_message__descriptor,
                                allocator, len, data);
}
void   keys_message__free_unpacked
                     (KeysMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &keys_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   message__init
                     (Message         *message)
{
  static const Message init_value = MESSAGE__INIT;
  *message = init_value;
}
size_t message__get_packed_size
                     (const Message *message)
{
  assert(message->base.descriptor == &message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t message__pack
                     (const Message *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t message__pack_to_buffer
                     (const Message *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Message *
       message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Message *)
     protobuf_c_message_unpack (&message__descriptor,
                                allocator, len, data);
}
void   message__free_unpacked
                     (Message *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor data_message__field_descriptors[1] =
{
  {
    "data",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(DataMessage, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned data_message__field_indices_by_name[] = {
  0,   /* field[0] = data */
};
static const ProtobufCIntRange data_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor data_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DataMessage",
  "DataMessage",
  "DataMessage",
  "",
  sizeof(DataMessage),
  1,
  data_message__field_descriptors,
  data_message__field_indices_by_name,
  1,  data_message__number_ranges,
  (ProtobufCMessageInit) data_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nullable_string__field_descriptors[1] =
{
  {
    "str",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NullableString, str),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nullable_string__field_indices_by_name[] = {
  0,   /* field[0] = str */
};
static const ProtobufCIntRange nullable_string__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor nullable_string__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NullableString",
  "NullableString",
  "NullableString",
  "",
  sizeof(NullableString),
  1,
  nullable_string__field_descriptors,
  nullable_string__field_indices_by_name,
  1,  nullable_string__number_ranges,
  (ProtobufCMessageInit) nullable_string__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor entry_message__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(EntryMessage, key),
    &nullable_string__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(EntryMessage, value),
    &data_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned entry_message__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange entry_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor entry_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EntryMessage",
  "EntryMessage",
  "EntryMessage",
  "",
  sizeof(EntryMessage),
  2,
  entry_message__field_descriptors,
  entry_message__field_indices_by_name,
  1,  entry_message__number_ranges,
  (ProtobufCMessageInit) entry_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor keys_message__field_descriptors[1] =
{
  {
    "keys",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(KeysMessage, n_keys),
    offsetof(KeysMessage, keys),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned keys_message__field_indices_by_name[] = {
  0,   /* field[0] = keys */
};
static const ProtobufCIntRange keys_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor keys_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "KeysMessage",
  "KeysMessage",
  "KeysMessage",
  "",
  sizeof(KeysMessage),
  1,
  keys_message__field_descriptors,
  keys_message__field_indices_by_name,
  1,  keys_message__number_ranges,
  (ProtobufCMessageInit) keys_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue message__operation_code__enum_values_by_number[8] =
{
  { "OP_BAD", "MESSAGE__OPERATION_CODE__OP_BAD", 0 },
  { "OP_SIZE", "MESSAGE__OPERATION_CODE__OP_SIZE", 10 },
  { "OP_DEL", "MESSAGE__OPERATION_CODE__OP_DEL", 20 },
  { "OP_GET", "MESSAGE__OPERATION_CODE__OP_GET", 30 },
  { "OP_PUT", "MESSAGE__OPERATION_CODE__OP_PUT", 40 },
  { "OP_GETKEYS", "MESSAGE__OPERATION_CODE__OP_GETKEYS", 50 },
  { "OP_HEIGHT", "MESSAGE__OPERATION_CODE__OP_HEIGHT", 60 },
  { "OP_ERROR", "MESSAGE__OPERATION_CODE__OP_ERROR", 99 },
};
static const ProtobufCIntRange message__operation_code__value_ranges[] = {
{0, 0},{10, 1},{20, 2},{30, 3},{40, 4},{50, 5},{60, 6},{99, 7},{0, 8}
};
static const ProtobufCEnumValueIndex message__operation_code__enum_values_by_name[8] =
{
  { "OP_BAD", 0 },
  { "OP_DEL", 2 },
  { "OP_ERROR", 7 },
  { "OP_GET", 3 },
  { "OP_GETKEYS", 5 },
  { "OP_HEIGHT", 6 },
  { "OP_PUT", 4 },
  { "OP_SIZE", 1 },
};
const ProtobufCEnumDescriptor message__operation_code__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Message.OperationCode",
  "OperationCode",
  "Message__OperationCode",
  "",
  8,
  message__operation_code__enum_values_by_number,
  8,
  message__operation_code__enum_values_by_name,
  8,
  message__operation_code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor message__field_descriptors[6] =
{
  {
    "op_code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Message, op_code),
    &message__operation_code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Message, content_case),
    offsetof(Message, key),
    NULL,
    &protobuf_c_empty_string,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    20,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Message, content_case),
    offsetof(Message, value),
    &data_message__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "entry",
    30,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Message, content_case),
    offsetof(Message, entry),
    &entry_message__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "keys",
    40,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Message, content_case),
    offsetof(Message, keys),
    &keys_message__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "int_result",
    50,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(Message, content_case),
    offsetof(Message, int_result),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned message__field_indices_by_name[] = {
  3,   /* field[3] = entry */
  5,   /* field[5] = int_result */
  1,   /* field[1] = key */
  4,   /* field[4] = keys */
  0,   /* field[0] = op_code */
  2,   /* field[2] = value */
};
static const ProtobufCIntRange message__number_ranges[6 + 1] =
{
  { 1, 0 },
  { 10, 1 },
  { 20, 2 },
  { 30, 3 },
  { 40, 4 },
  { 50, 5 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Message",
  "Message",
  "Message",
  "",
  sizeof(Message),
  6,
  message__field_descriptors,
  message__field_indices_by_name,
  6,  message__number_ranges,
  (ProtobufCMessageInit) message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
